// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygrhdxjmmjxhehwkmety.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlncmhkeGptbWp4aGVod2ttZXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTc5NDgsImV4cCI6MjA3MzY5Mzk0OH0.h3fxqZL2kcQW6vadFylnE2plX2Tqsadi9mAxDyZKQvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});